FROM openjdk:17.0.2-jdk-slim as builder

WORKDIR /app

COPY gradle gradle/
COPY *.gradle.kts gradlew ./

RUN ./gradlew --help > /dev/null

COPY src src/

RUN ./gradlew clean build -x test
RUN mkdir /app/extracted && \
    java -Djarmode=layertools -jar /app/build/libs/spring-demo.jar extract --destination /app/extracted

FROM bellsoft/liberica-openjre-alpine:17 as temurin-jdk

WORKDIR /app

COPY --from=builder /app/extracted/dependencies /app/
COPY --from=builder /app/extracted/spring-boot-loader /app/
COPY --from=builder /app/extracted/snapshot-dependencies /app/
COPY --from=builder /app/extracted/application /app/

EXPOSE 8080
ENTRYPOINT [ "java", "org.springframework.boot.loader.JarLauncher" ]